baseURL = "https://louisnguyencloud.com/"
defaultContentLanguage = "en"
title = "Louis Nguyen"
theme = "hugo-theme-console"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Certifications"
url = "/certifications/"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 3