baseURL = "http://louisnguyencloud.com/"
defaultContentLanguage = "en"
title = "Louis Nguyen"
theme = "hugo-theme-console"

[[menu.main]]
name = "Home"
url = "/"

[[menu.main]]
name = "Projects"
url = "/projects/"

[[menu.main]]
name = "About"
url = "/about/"